- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: ignition.msgs.Clock
  direction: GZ_TO_ROS
- ros_topic_name: /pingpong/joint_states
  gz_topic_name: /pingpong/joint_states
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: ignition.msgs.Model
  direction: GZ_TO_ROS
- ros_topic_name: /pingpong/yaw_cmd
  gz_topic_name: /pingpong/yaw_cmd
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /pingpong/pitch_cmd
  gz_topic_name: /pingpong/pitch_cmd
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /pingpong/feeder_cmd
  gz_topic_name: /pingpong/feeder_cmd
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /pingpong/wheel_1_cmd
  gz_topic_name: /pingpong/wheel_1_cmd
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /pingpong/wheel_2_cmd
  gz_topic_name: /pingpong/wheel_2_cmd
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /pingpong/wheel_3_cmd
  gz_topic_name: /pingpong/wheel_3_cmd
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /pingpong/fire_request
  gz_topic_name: /pingpong/fire
  ros_type_name: std_msgs/msg/Bool
  gz_type_name: ignition.msgs.Boolean
  direction: ROS_TO_GZ
- ros_topic_name: /pingpong/shot_count
  gz_topic_name: /pingpong/shot_count
  ros_type_name: std_msgs/msg/UInt32
  gz_type_name: ignition.msgs.UInt32
  direction: GZ_TO_ROS
- ros_topic_name: /pingpong/ball_status
  gz_topic_name: /pingpong/ball_status
  ros_type_name: std_msgs/msg/String
  gz_type_name: ignition.msgs.StringMsg
  direction: GZ_TO_ROS
- ros_topic_name: /pingpong/dynamic_poses
  gz_topic_name: /world/pingpong_world/dynamic_pose/info
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: ignition.msgs.Pose_V
  direction: GZ_TO_ROS
